export function makeBoard() {
  return [
    [
      {
        has_bomb: false,
        bombs_around: 1,
        is_open: false,
        row: 0,
        col: 0,
      },
      {
        has_bomb: true,
        bombs_around: 0,
        is_open: false,
        row: 0,
        col: 1,
      },
      {
        has_bomb: false,
        bombs_around: 1,
        is_open: false,
        row: 0,
        col: 2,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 0,
        col: 3,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 0,
        col: 4,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 0,
        col: 5,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 0,
        col: 6,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 0,
        col: 7,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 0,
        col: 8,
      },
    ],
    [
      {
        has_bomb: false,
        bombs_around: 1,
        is_open: false,
        row: 1,
        col: 0,
      },
      {
        has_bomb: false,
        bombs_around: 1,
        is_open: false,
        row: 1,
        col: 1,
      },
      {
        has_bomb: false,
        bombs_around: 1,
        is_open: false,
        row: 1,
        col: 2,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 1,
        col: 3,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 1,
        col: 4,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 1,
        col: 5,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 1,
        col: 6,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 1,
        col: 7,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 1,
        col: 8,
      },
    ],
    [
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 2,
        col: 0,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 2,
        col: 1,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 2,
        col: 2,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 2,
        col: 3,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 2,
        col: 4,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 2,
        col: 5,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 2,
        col: 6,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 2,
        col: 7,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 2,
        col: 8,
      },
    ],
    [
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 3,
        col: 0,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 3,
        col: 1,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 3,
        col: 2,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 3,
        col: 3,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 3,
        col: 4,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 3,
        col: 5,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 3,
        col: 6,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 3,
        col: 7,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 3,
        col: 8,
      },
    ],
    [
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 4,
        col: 0,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 4,
        col: 1,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 4,
        col: 2,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 4,
        col: 3,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 4,
        col: 4,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 4,
        col: 5,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 4,
        col: 6,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 4,
        col: 7,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 4,
        col: 8,
      },
    ],
    [
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 5,
        col: 0,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 5,
        col: 1,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 5,
        col: 2,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 5,
        col: 3,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 5,
        col: 4,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 5,
        col: 5,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 5,
        col: 6,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 5,
        col: 7,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 5,
        col: 8,
      },
    ],
    [
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 6,
        col: 0,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 6,
        col: 1,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 6,
        col: 2,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 6,
        col: 3,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 6,
        col: 4,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 6,
        col: 5,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 6,
        col: 6,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 6,
        col: 7,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 6,
        col: 8,
      },
    ],
    [
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 7,
        col: 0,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 7,
        col: 1,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 7,
        col: 2,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 7,
        col: 3,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 7,
        col: 4,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 7,
        col: 5,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 7,
        col: 6,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 7,
        col: 7,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 7,
        col: 8,
      },
    ],
    [
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 8,
        col: 0,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 8,
        col: 1,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 8,
        col: 2,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 8,
        col: 3,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 8,
        col: 4,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 8,
        col: 5,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 8,
        col: 6,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 8,
        col: 7,
      },
      {
        has_bomb: false,
        bombs_around: 0,
        is_open: false,
        row: 8,
        col: 8,
      },
    ],
  ];
}
